/**
 * Created by developercomputer on 11.01.16.
 */
export default [
  { name: "Aguascalientes",           code: "AG", sizeIndex: 0.75  },
  { name: "Baja California Norte",    code: "BN", sizeIndex: 1.00  },
  { name: "Baja California Sur",      code: "BS", sizeIndex: 1.00  },
  { name: "Campeche",                 code: "CM", sizeIndex: 1.00  },
  { name: "Chiapas",                  code: "CP", sizeIndex: 1.00  },
  { name: "Chihuahua",                code: "CH", sizeIndex: 1.25  },
  { name: "Coahuila",                 code: "CA", sizeIndex: 1.00  },
  { name: "Colima",                   code: "CL", sizeIndex: 0.75  },
  { name: "Ciudad de México",         code: "DF", sizeIndex: 0.75  },
  { name: "Durango",                  code: "DU", sizeIndex: 1.00  },
  { name: "Guanajuato",               code: "GT", sizeIndex: 1.00  },
  { name: "Guerrero",                 code: "GR", sizeIndex: 1.00  },
  { name: "Hidalgo",                  code: "HI", sizeIndex: 1.00  },
  { name: "Jalisco",                  code: "JA", sizeIndex: 1.00  },
  { name: "Michoacán",                code: "MC", sizeIndex: 1.00  },
  { name: "Edo. de México",           code: "MX", sizeIndex: 0.75  },
  { name: "Morelos",                  code: "MR", sizeIndex: 1.00  },
  { name: "Nayarit",                  code: "NA", sizeIndex: 1.00  },
  { name: "Nuevo León",               code: "NL", sizeIndex: 1.00  },
  { name: "Oaxaca",                   code: "OA", sizeIndex: 1.00  },
  { name: "Puebla",                   code: "PU", sizeIndex: 1.00  },
  { name: "Querétaro",                code: "QE", sizeIndex: 0.75  },
  { name: "Quintana Roo",             code: "QR", sizeIndex: 1.00  },
  { name: "San Luis Potosí",          code: "SL", sizeIndex: 1.00  },
  { name: "Sinaloa",                  code: "SI", sizeIndex: 1.00  },
  { name: "Sonora",                   code: "SO", sizeIndex: 1.25  },
  { name: "Tabasco",                  code: "TB", sizeIndex: 1.00  },
  { name: "Tamaulipas",               code: "TM", sizeIndex: 1.00  },
  { name: "Tlaxcala",                 code: "TL", sizeIndex: 0.75  },
  { name: "Veracruz",                 code: "VE", sizeIndex: 1.00  },
  { name: "Yucatán",                  code: "YU", sizeIndex: 1.00  },
  { name: "Zacatecas",                code: "ZA", sizeIndex: 1.00  }
];
